version: '3'
services:
  kafka_ms:
    build: .
    command: nameko run --config src/config.yml src.service
    volumes:
      - .:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      SERVICE_NAME: "micro_service_A"
      TOPIC_NAME: "example_topic"
    networks:
      - backend

networks:
  backend:
    external: true
